package reservationBillet.gui;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

import reservationBillet.agent.AgentClient;
import reservationBillet.model.CriteresClient;


public class ClientGUI extends javax.swing.JFrame{



	    AgentClient clientAgent;

	    public ClientGUI(AgentClient clientAgent) {
	        this.clientAgent = clientAgent;
	        initComponents();
	        setSize(370, 350);
	        //setFocusable(true);
	    }

	    boolean EstVide() {
	        boolean rep = true;
	        if ((String) txtFieldAeroportd.getText() !=""
	                || (String) txtFieldAeroporta.getText() != "" )
	        {
	            rep = false;
	        }else{
	            rep = true;
	        }
	        return rep;
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings({ "unchecked", "rawtypes" })
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        txtFieldAeroportd = new javax.swing.JTextField();
	        txtFieldAeroporta = new javax.swing.JTextField();
	        btnRechercher = new javax.swing.JButton();
	        btnAnnuler = new javax.swing.JButton();
	        typVol = new javax.swing.JComboBox();
	        classevol = new javax.swing.JComboBox();
	        nbplace = new javax.swing.JSpinner();
	        datD = new javax.swing.JFormattedTextField();
	        datR = new javax.swing.JFormattedTextField();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel5 = new javax.swing.JLabel();
	        jLabel6 = new javax.swing.JLabel();
	        jLabel7 = new javax.swing.JLabel();
	        jLabel8 = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        txtFieldAeroportd.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                txtFieldAeroportActionPerformed(evt);
	            }
	        });

	        btnRechercher.setText("chercher");
	        btnRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                btnRechercherMouseClicked(evt);
	            }
	        });
	        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnRechercherActionPerformed(evt);
	            }
	        });

	        btnAnnuler.setText("Annuler");
	        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnAnnulerActionPerformed(evt);
	            }
	        });

	        typVol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alle Simple", "Alle-Retour" }));

	        classevol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economique", "Business" }));
	        
	        datD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

	        datR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
	        datR.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                datFinActionPerformed(evt);
	            }
	        });

	        jLabel1.setText("Critères de recherche");

	        jLabel2.setText("Classe vol");

	        jLabel3.setText("Type vol");

	        jLabel4.setText("Date de depart");

	        jLabel5.setText("Date de Retour");

	        jLabel6.setText("Aeroport depart");

	        jLabel7.setText("Aeroport d'arrivée");
	        
	        jLabel8.setText("Nombre de place");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(37, 37, 37)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))       
	                        .addGap(18, 18, 18)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                                .addComponent(btnRechercher)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(btnAnnuler)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(datR, javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(datD, javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(typVol, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(classevol, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(txtFieldAeroportd, javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(txtFieldAeroporta, javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(nbplace, javax.swing.GroupLayout.Alignment.TRAILING))
	                            .addGap(59, 59, 59))))
	            				
	                             
	  	  
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(14, 14, 14)
	                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)	               
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                    .addComponent(classevol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jLabel2))	                
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                    .addComponent(typVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jLabel3))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(datD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel4))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(datR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel5))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		                    .addComponent(txtFieldAeroportd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addGap(18, 18, 18)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(txtFieldAeroporta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
			                .addGap(18, 18, 18)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(nbplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel8))	             
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(btnRechercher)
	                    .addComponent(btnAnnuler))
	                .addGap(32, 32, 32))
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	    private void datFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datFinActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_datFinActionPerformed

	    private void txtFieldAeroportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAeroportActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_txtFieldAeroportActionPerformed

	    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
	        // TODO add your handling code here: 
	        if (EstVide()) {
	            infoBox("Veuillez remplir tous les champs");
	        }else{
	                    btnRechercher.setEnabled(false);
	        CriteresClient besoinClient = new CriteresClient();
	   
	        besoinClient.setAeroportDepart(txtFieldAeroportd.getText());
	        besoinClient.setAeroportArrivee(txtFieldAeroporta.getText());
	        besoinClient.setTypevol((String)typVol.getSelectedItem());
	        besoinClient.setClassevol((String)classevol.getSelectedItem());
	    
	        String pattern = "dd/MM/yyyy";
	        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
	        String date1 = simpleDateFormat.format(datD.getValue());
	        datD.setText(date1);
	        String date2 = simpleDateFormat.format(datR.getValue());
	        datR.setText(date2);
	       
	        besoinClient.setDatRetour((Date) datR.getValue());
	        besoinClient.setDatDepart((Date) datD.getValue());
	       
	        besoinClient.setNbplace((int) nbplace.getValue());
	        afficheBesoinClient(besoinClient);
	        clientAgent.setUserRequest(besoinClient);
	        }

	    }//GEN-LAST:event_btnRechercherActionPerformed

	    private void btnRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechercherMouseClicked
	        // TODO add your handling code here:      
	    }//GEN-LAST:event_btnRechercherMouseClicked

	    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
	        // TODO add your handling code here:
	        this.setVisible(false);
	    }//GEN-LAST:event_btnAnnulerActionPerformed

	    public void infoBox(String infoMessage) {
	        JOptionPane.showMessageDialog(this, infoMessage, "Aucune offre ", JOptionPane.INFORMATION_MESSAGE);
	    }

	    void afficheBesoinClient(CriteresClient bs) {
	        System.out.println("Agent client : Affichage du besoin client");
	        System.out.println("Classe vol = " + bs.getClassevol());
	        System.out.println("Type vol = " + bs.getTypevol());
	        
	        System.out.println("Date depart = " + bs.getDatDepart());
	        System.out.println("Date Retour = " + bs.getDatRetour());
	        System.out.println("Aeroport depart = " + bs.getAeroportDepart());
	        System.out.println("Aeroport Arrivee= " + bs.getAeroportArrivee());
	        System.out.println("Nombre de place = " + bs.getNbplace());
	    }

	    public void clearZoneEdit() {
	        btnRechercher.setEnabled(true);
	        txtFieldAeroportd.setText("");
	        txtFieldAeroporta.setText("");
	        datD.setText("");
	        datR.setText("");
	     
	        nbplace.setValue(0);
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JButton btnAnnuler;
	    private javax.swing.JButton btnRechercher;
	    private javax.swing.JComboBox typVol;
	    private javax.swing.JComboBox classevol;
	    private javax.swing.JFormattedTextField datD;
	    private javax.swing.JFormattedTextField datR;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JSpinner nbplace;	
	    private javax.swing.JTextField txtFieldAeroportd;
	    private javax.swing.JTextField txtFieldAeroporta;
	    // End of variables declaration//GEN-END:variables
	}
